from typing import Final

windowTitle: Final[str] = "MMA"
menuTitle: Final[str] = "MMA"
btnStart: Final[str] = "COMMENCER LE JEU"
btnOptions: Final[str] = "OPTIONS"
btnQuit: Final[str] = "QUITTER"
gameTitle: Final[str] = "JEU"
gameSubtitle: Final[str] = "Mode Combat Bientôt Disponible!"
optionsTitle: Final[str] = "OPTIONS"
optionsSubtitle: Final[str] = "Paramètres Bientôt Disponibles!"
optionsControls: Final[str] = "CONTROLES"
optionsJump: Final[str] = "SAUTER"
optionsSlide: Final[str] = "GLISSER"
optionsReset: Final[str] = "REINITIALISER"
optionsBack: Final[str] = "RETOUR"
optionsPressKey: Final[str] = "APPUYEZ..."
optionsController: Final[str] = "MANETTE"
optionsJoyJump: Final[str] = "Sauter (Manette)"
optionsJoySlide: Final[str] = "Glisser (Manette)"
optionsJoyReset: Final[str] = "REINITIALISER MANETTE"
optionsNoController: Final[str] = "Aucune manette connectée"
optionsPressButton: Final[str] = "APPUYEZ SUR UN BOUTON..."

hudJump: Final[str] = "Sauter"
hudSlide: Final[str] = "Glisser"
instructionEsc: Final[str] = "Appuyez sur ÉCHAP pour revenir au menu"

gameOver: Final[str] = "ATTRAPÉ!"
gameRestartKey: Final[str] = "Appuyez sur R pour recommencer"
gameRestartButton: Final[str] = "Appuyez sur {button} pour recommencer"

rpcGameName: Final[str] = "MMA"
rpcInMenu: Final[str] = "Dans le menu principal"
rpcPlaying: Final[str] = "En train de jouer | Score: {score}"
rpcGameOver: Final[str] = "Game Over | Score Final: {score}"
