from typing import Final

windowTitle: Final[str] = "BSD Runner"
menuTitle: Final[str] = "BSD Runner"
btnPlay: Final[str] = "JOUER"
btnOptions: Final[str] = "OPTIONS"
btnQuit: Final[str] = "QUITTER"
levelSelectTitle: Final[str] = "SÉLECTION DE NIVEAU"
levelCompleted: Final[str] = "COMPLÉTÉ"
levelLocked: Final[str] = "VERROUILLÉ"
levelAvailable: Final[str] = "DISPONIBLE"
levelTarget: Final[str] = "Objectif: {score} pts"
gameTitle: Final[str] = "JEU"
gameSubtitle: Final[str] = "Mode Combat Bientôt Disponible!"
optionsTitle: Final[str] = "OPTIONS"
optionsSubtitle: Final[str] = "Paramètres Bientôt Disponibles!"
optionsControls: Final[str] = "CONTROLES"
optionsJump: Final[str] = "SAUTER"
optionsSlide: Final[str] = "GLISSER"
optionsRestart: Final[str] = "RECOMMENCER"
optionsSound: Final[str] = "SON"
optionsReset: Final[str] = "REINITIALISER"
optionsBack: Final[str] = "RETOUR"
optionsPressKey: Final[str] = "APPUYEZ..."
optionsController: Final[str] = "MANETTE"
optionsJoyJump: Final[str] = "Sauter (Manette)"
optionsJoySlide: Final[str] = "Glisser (Manette)"
optionsJoyReset: Final[str] = "REINITIALISER MANETTE"
optionsNoController: Final[str] = "Aucune manette connectée"
optionsPressButton: Final[str] = "APPUYEZ SUR UN BOUTON..."

hudJump: Final[str] = "Sauter"
hudSlide: Final[str] = "Glisser"
hudDoubleJump: Final[str] = "Double Saut"
hudShoot: Final[str] = "Tirer"
instructionEsc: Final[str] = "Appuyez sur ÉCHAP pour revenir au menu"

gameOver: Final[str] = "ATTRAPÉ!"
gameRestartKey: Final[str] = "Appuyez sur {key} pour recommencer"
gameRestartButton: Final[str] = "Appuyez sur {button} pour recommencer"

levelComplete: Final[str] = "NIVEAU TERMINÉ!"
levelCompleteRestart: Final[str] = "Appuyez sur {key} pour recommencer"

gameOverMenuKey: Final[str] = "Appuyez sur ÉCHAP pour le menu"
gameOverMenuButton: Final[str] = "Appuyez sur {button} pour le menu"

rpcGameName: Final[str] = "BSD Runner"
rpcInMenu: Final[str] = "Dans le menu principal"
rpcPlaying: Final[str] = "En train de jouer | Score: {score}"
rpcGameOver: Final[str] = "Game Over | Score Final: {score}"
